# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'discuss.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 20, 791, 571))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(321, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.post_table = QtWidgets.QTableWidget(self.frame_2)
        self.post_table.setMaximumSize(QtCore.QSize(250, 16777215))
        self.post_table.setObjectName("post_table")
        self.post_table.setColumnCount(0)
        self.post_table.setRowCount(0)
        self.verticalLayout.addWidget(self.post_table)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.post_line = QtWidgets.QLineEdit(self.frame_3)
        self.post_line.setMinimumSize(QtCore.QSize(211, 71))
        self.post_line.setObjectName("post_line")
        self.horizontalLayout.addWidget(self.post_line)
        self.post_button = QtWidgets.QPushButton(self.frame_3)
        self.post_button.setMinimumSize(QtCore.QSize(51, 41))
        self.post_button.setMaximumSize(QtCore.QSize(51, 41))
        self.post_button.setObjectName("post_button")
        self.horizontalLayout.addWidget(self.post_button)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.reply_table = QtWidgets.QTableWidget(self.frame_4)
        self.reply_table.setMaximumSize(QtCore.QSize(400, 16777215))
        self.reply_table.setObjectName("reply_table")
        self.reply_table.setColumnCount(0)
        self.reply_table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.reply_table)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.reply_line = QtWidgets.QLineEdit(self.frame_5)
        self.reply_line.setMinimumSize(QtCore.QSize(211, 71))
        self.reply_line.setObjectName("reply_line")
        self.horizontalLayout_2.addWidget(self.reply_line)
        self.reply_button = QtWidgets.QPushButton(self.frame_5)
        self.reply_button.setMinimumSize(QtCore.QSize(51, 41))
        self.reply_button.setMaximumSize(QtCore.QSize(51, 41))
        self.reply_button.setObjectName("reply_button")
        self.horizontalLayout_2.addWidget(self.reply_button)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout_3.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "模块"))
        self.post_button.setText(_translate("MainWindow", "发布"))
        self.reply_button.setText(_translate("MainWindow", "回复"))
